[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# PWA Support
[[plugins]]
  package = "@netlify/plugin-pwa"
  [plugins.inputs]
    enable = true
    sw_src = "public/service-worker.js"

# Scheduled functions
[[plugins]]
  package = "@netlify/plugin-functions-schedule"

# Strategy Summary Bot - Run weekly on Sunday at 5 AM UTC
[[scheduled-functions]]
  schedule = "0 5 * * SUN"
  name = "ai-strategy-summary"

# Trade Feedback Bot - Run Mondays at 8 AM UTC
[[scheduled-functions]]
  schedule = "0 8 * * MON"
  name = "ai-trade-feedback"

# Vision Chart Labeler - Run daily at 2 AM UTC
[[scheduled-functions]]
  schedule = "0 2 * * *"
  name = "ai-chart-labeler"

# LMS Coach - Run Wednesdays and Saturdays at 7 AM UTC
[[scheduled-functions]]
  schedule = "0 7 * * WED,SAT"
  name = "ai-lms-coach"

# Crypto Payment Verifier - Run every 15 minutes
[[scheduled-functions]]
  schedule = "*/15 * * * *"
  name = "verify-crypto-payment"

# Market Sync - Run every 4 hours
[[scheduled-functions]]
  schedule = "0 */4 * * *"
  name = "market-sync"

# Backtest Queue Worker - Run every 5 minutes
[[scheduled-functions]]
  schedule = "*/5 * * * *"
  name = "backtest-worker"

# Notification Watchdog - Run hourly
[[scheduled-functions]]
  schedule = "0 * * * *"
  name = "notification-watchdog"

# Environment variable configuration
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# PWA headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.openai.com https://*.insightflow.ai; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://*.tradingview.com; font-src 'self' data:; manifest-src 'self'" 