name: Build Android APK

on:
  push:
    branches: [ lovable-react-only ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npx vite build
      
    - name: Install Capacitor
      run: npm install @capacitor/core @capacitor/cli @capacitor/android
      
    - name: Add Android platform
      run: npx cap add android
      
    - name: Sync Android
      run: npx cap sync android
      
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: insightflow-trading-app
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: android/app/build/outputs/apk/debug/app-debug.apk
        body: |
          ## InsightFlow Trading App APK
          
          ### What's New
          - AI-powered trading intelligence
          - Real-time market analysis
          - Strategy builder & backtesting
          - Portfolio management
          
          ### Installation
          1. Download the APK
          2. Enable "Unknown sources" in Android settings
          3. Install the APK
          
          ### Features
          - 📊 Real-time market data
          - 🤖 AI trading suggestions
          - 📈 Strategy backtesting
          - 📱 Mobile-optimized interface
          - 🔒 Secure authentication
          
          Built with React, Capacitor, and AI technology.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 