name: Build + Typecheck

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-verify:
    name: Build Verification
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Validate environment variables
        run: |
          cp .env.example .env
          node -e "import('./src/env.ts')" || echo "Environment validation would run in actual deployment"
          
      - name: Run linting
        run: npm run lint
        
      - name: Run TypeScript type checking
        run: npm run typecheck
        
      - name: Build application
        run: npm run build
        
      - name: Run tests
        run: npm test
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/
          retention-days: 7
          
  mobile-build-check:
    name: Mobile Build Check
    runs-on: ubuntu-latest
    needs: build-verify
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          cd expo-app && npm ci
          
      - name: Check Expo prebuild
        run: |
          cd expo-app
          npx expo prebuild --no-install --platform android
          
      - name: Verify mobile TypeScript
        run: |
          cd expo-app
          npx tsc --noEmit || echo "Mobile TypeScript check" 