name: Lovable QA CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  lovable:
    name: Lovable Continuous QA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Lovable Web Tests
        run: npx lovable test:web --config lovable.config.js

      - name: Run Lovable Mobile Tests
        run: npx lovable test:mobile --config lovable.config.js

      - name: Run Lovable Backend Tests
        run: npx lovable test:backend --config lovable.config.js

      - name: Upload Lovable Quality Report
        uses: actions/upload-artifact@v3
        with:
          name: lovable-report
          path: .lovable-report

    # Fail the job if any lovable test fails (Lovable CLI exits non-zero) 